### ISSUE TITLE
Support for global custom options

### ISSUE THREAD

**Issue by ydcjeff** [privatenumber/cleye#1]
### Feature request

Thanks for this type-safe library. Support global custom options like `vite dev --debug`, `vite build --debug`.
I try replicating Vite CLI with this library. Currently, there is no an easy way to declare global options.

### Why?

The existing libraries/frameworks already support this. Global options is a core part of a CLI app.

### Alternatives

create a shared global options object and used in every command.

**Comment by privatenumber** [comment]
Thanks for the feature request.

As you suggested in the alternative approach, I think using plain objects is a fairly easy and intuitive API:

```ts
// global-options.ts
export const globalOptions = {
	debug: Boolean
}


// commands/dev.ts
import { command } from 'cleye'
import { globalOptions } from '../global-options'

export const devCommand = command({
	name: 'dev',
	flags: {
		...globalOptions,

		// more options
	}
})

// commands/build.ts
import { command } from 'cleye'
import { globalOptions } from '../global-options'

export const buildCommand = command({
	name: 'build',
	flags: {
		...globalOptions,

		// more options
	}
})
```

I think this is not only simple, but encourages maintainable code because it doesn't introduce additional APIs and a learning curve to working with Cleye.

Did you have a specific API in mind?

**Comment by ydcjeff** [comment]
Thanks for the response. Yes, a global shared options shine in large CLI apps.

For the API, I am thinking like:
```js
// main cli
cli({
  flags: {
    option: {
      ...,
      expose: true // or false, expose this option to all subcommands
    }
  }
})

// command
command({
  flags: {
    option: {
      ...,
      expose: true // or false, expose this option to all subcommands
    }
  }
})
```
But that could make the users unable to find where that options come from in the large CLI apps. If TypeScript can help here, that would be great.

**Comment by privatenumber** [comment]
I'm confused why you're proposing this API, because instead of describing the problem it solves, you highlight a major flaw that users will have difficulty resolving implicitly inherited flags in large CLI apps (which I agree with).

What's the benefit of this API in comparison to doing an object spread (eg. `...sharedOptions`)?

**Comment by privatenumber** [comment]
Sorry but I'm having trouble seeing the benefits here. I'm also confused why you're proposing this API, because instead of describing its benefits, you highlight a major flaw that users will have difficulty resolving implicitly inherited flags in large CLI apps (which I agree with).

What problem does this API solve that an object spread (eg. `...sharedOptions`) can't?

**Comment by ydcjeff** [comment]
I think the proposed API will work well for a small number of options than object spread. But I agree with you about maintainable code and no additional API, so I am going to close this feature request.

Thanks for the discussion.
